project_name: go-cpe-dictionary
release:
  github:
    owner: vulsio
    name: go-cpe-dictionary
builds:
- goos:
  - linux
  goarch:
  - amd64
  main: .
  ldflags: -s -w -X github.com/vulsio/go-cpe-dictionary/config.Version={{.Version}} -X github.com/vulsio/go-cpe-dictionary/config.Revision={{.Commit}}
  binary: go-cpe-dictionary
archives:
- name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  files:
  - LICENSE
  - README*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
